services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manutencao
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  sensor-simulator:
    build:
      context: ../simulator
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  api:
    build:
      context: ../backend/ManutencaoPreditiva.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=manutencao;Username=user;Password=password
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend/manutencao-preditiva-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
